name: Build and deploy Node.js app to Azure Web App - C8VortexUI

on:
  push:
    branches:
      - master
      - master2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip the application files 
        run: zip -r node-app.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip node-app.zip

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'C8VortexUI'  # Replace with your actual Azure Web App name
          slot-name: 'Production' # Replace with your actual deployment slot name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_357246274E8040EDA2A4C58BA4338205 }}
          package: .

  deploy_development:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master2'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip node-app.zip

      - name: Deploy to Azure Web App (Development)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dev-vortexui'  # Replace with your actual Azure Web App name
          slot-name: 'Production' # Replace with your actual deployment slot name for development
          publish-profile: ${{ secrets.AZURE_DEVELOPMENT_SERVER }}
          package: .